#######################
#### eureka
#######################
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    

######################
#### SERVIDOR
######################
server:
  port: 8080
  

#####################
#### JPA /DATASOURCE
####################  
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: root
    url: jdbc:mariadb://localhost:3306/microservice-flowers
    username: root
    
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  application:
    name: flowers-store
    
  service-url:
   defaultZone: http://localhost:8761/eureka
  

################################
#### LOGGIN 
################################

logging:
  file:
    name: logs/application.log

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
