server:
  port: 8081
 
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
     defaultZone: http://localhost:8761/eureka
     
spring:     
  application:
    name: provider
#  profiles:
#    active: default
#  cloud:
#    config:
    
#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    password: root
#    url: jdbc:mariadb://localhost:3306/microservice-provider
#    username: root
#    
#  jpa:
#    hibernate:
#      ddl-auto: update
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true
logging:
  file:
    name: logs/application.log
    

